name: Deploy to Dokploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /app
          git pull origin main

      - name: Restart app container
        run: |
          docker restart inventory-management-dukan-vhhgqi.1.b07vbwnoefjcpig0mumekatc0
